'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {fixture}=require('./sdk.cjs'),{createLoader}=require('./loader.cjs');
const root=path.resolve(__dirname,'../..'),vector=JSON.parse(fs.readFileSync(path.join(root,'scripts/guest-summary/booking-guest-offer-public-vector.json')));
const admission=JSON.parse(fs.readFileSync(path.join(__dirname,'business-admission.json')));
function setup(initial={}){const f=fixture({initial:{GuestBookingFinancialRevisions:[vector.revisionRow],Rooms:[{_id:'suite',roomCode:'adventure_suite'}],...initial},secretValues:vector.secrets}),clock={now:vector.now};const loader=createLoader(f,clock,admission);return {f,clock,loader,load:n=>loader.load('velo/backend/'+n+'.js')};}
async function e2e(){const s=setup(),connector=s.load('guestBookingSummaryStatusConnector').createGuestBookingSummaryStatusConnector();const {priceGroups,...input}=vector.purchase;const offer=await connector.prepare({...input,summaryRooms:vector.summaryRooms});assert.equal(offer.status,'OFFER');const accepted=await connector.confirm(offer);assert.equal(accepted.status,'ACCEPTED_PENDING');assert.equal(s.f.snapshot().GuestBookingAcceptances.length,1);assert.notEqual((await connector.readStatus(offer)).status,'CONFIRMED');const recovery=s.load('guestBookingCompletionRecovery');const visits=[];for(let i=0;i<64&&!s.f.snapshot().GuestBookingCompletions.length;i++)visits.push(await recovery.recoverGuestBookingCompletions());fs.writeFileSync(path.join(__dirname,'evidence/business-prefix.json'),JSON.stringify({accepted,visits,db:s.f.snapshot(),trace:s.f.trace},null,2));assert.equal(s.f.snapshot().GuestBookingCompletions.length,1,'actual recovery must produce completion receipt');assert.equal((await connector.readStatus(offer)).status,'CONFIRMED');const search=await s.load('search.web').searchAvailability(vector.purchase.checkIn,vector.purchase.checkOut);assert.equal(search.ok,true);assert.equal(search.results.find(x=>x.roomCode==='adventure_suite')?.maxQty??0,0,'Search must reserve suites 3/4 and preserve owner-only suite 5');return {status:'PASS',id:'E2E01'};}
if(require.main===module)e2e().then(x=>console.log(JSON.stringify(x))).catch(e=>{console.error(e.stack);process.exitCode=1;});
module.exports={setup,e2e,vector};
