'use strict';
const assert=require('node:assert/strict');const {harness}=require('./page-wiring.cjs');
const tick=()=>new Promise(r=>setImmediate(r));
async function cart(){const h=await harness();await h.click();const old=h.rows.at(-2);await old.itemEl('#removeBtn').fire();await tick();assert.equal(h.el('#summaryRoomsRepeater').data.length,1,'remove only the selected original group, not all same-class groups');assert.match(h.el('#btnContinue').label,/Review/);await old.itemEl('#removeBtn').fire();await tick();assert.equal(h.el('#summaryRoomsRepeater').data.length,1,'detached old row cannot remove remaining group');await h.click();assert.equal(h.calls.prepare,2);assert.equal(h.calls.confirm,0);assert.equal(h.el('#grandTotal').text,'$235.00');await h.click();const frozen=h.el('#summaryRoomsRepeater').data.length;await h.rows.at(-1).itemEl('#removeBtn').fire();await tick();assert.equal(h.el('#summaryRoomsRepeater').data.length,frozen,'pending cart frozen');return h.calls;}
async function unknown(){let fail=true;const h=await harness({before:async kind=>{if(kind==='confirm'&&fail){fail=false;throw Error('transport before dispatch');}}});await h.click();await h.click();assert.match(h.status(),/unknown/i);assert.equal(h.s.f.snapshot().GuestBookingAcceptances.length,0);await h.click();assert.equal(h.calls.confirm,2,'UNKNOWN acceptance retries same credential, never a new offer');assert.equal(h.s.f.snapshot().GuestBookingAcceptances.length,1);assert.match(h.status(),/still being saved/);assert.equal(h.calls.prepare,1);return h.calls;}
async function promo(){let release;const gate=new Promise(r=>release=r);let entered=false;const h=await harness({promo:async()=>{entered=true;await gate;return {valid:true,discount:0.5,description:'inert late reply'};}});await h.click();h.el('#promoCode').value='OLD';await h.el('#promoCode').fire('input');const applying=h.el('#btnApplyPromo').fire();for(let i=0;i<100&&!entered;i++)await tick();assert.ok(entered);h.el('#promoCode').value='';await h.el('#promoCode').fire('input');release();await applying;await tick();await tick();assert.doesNotMatch(h.el('#promoStatus').text,/OLD applied/,'stale promo response must not apply to edited input');await h.click();assert.equal(h.calls.confirm,0);assert.equal(h.el('#grandTotal').text,'$470.00');assert.ok((h.el('#promoCode').handlers.keypress?.length||0)+(h.el('#promoCode').handlers.keydown?.length||0)<=1,'one Enter event family');return h.calls;}
async function edits(){let release,entered=false;const gate=new Promise(r=>release=r);const h=await harness({after:async kind=>{if(kind==='prepare'&&!entered){entered=true;await gate;}}});const first=h.click();for(let i=0;i<100&&!entered;i++)await tick();assert.ok(entered);await h.click();assert.equal(h.calls.prepare,1,'duplicate prepare suppressed');h.el('#inputGuestName').value='Edited Guest';await h.el('#inputGuestName').fire('input');release();await first;assert.doesNotMatch(h.el('#btnContinue').label,/Confirm/,'late stale offer cannot restore confirm');assert.equal(h.s.f.snapshot().GuestBookingAcceptances.length,0);await h.click();assert.equal(h.calls.prepare,2);h.el('#bookingNotes').value='Changed without event';await h.click();assert.equal(h.calls.prepare,3,'snapshot comparison catches unreported edit');assert.equal(h.calls.confirm,0);await Promise.all([h.click(),h.click(),h.click()]);assert.equal(h.calls.confirm,1,'one confirmation despite simultaneous callbacks');assert.equal(h.s.f.snapshot().GuestBookingAcceptances.length,1);h.el('#inputGuestName').value='Programmatic after acceptance';await h.el('#inputGuestName').fire('input');await h.click();assert.equal(h.calls.prepare,3,'accepted operation cannot be invalidated');assert.equal(h.calls.refresh,1);return h.calls;}
async function required(){const h=await harness(),ids=['inputGuestName','inputGuestEmail','inputGuestPhone'],values=['Guest','guest@example.test','1234567'];for(let mask=0;mask<7;mask++){ids.forEach((id,i)=>h.el('#'+id).value=mask&(1<<i)?values[i]:'');await h.click();assert.equal(h.status(),'Please enter the required information to complete your booking');assert.equal(h.calls.prepare,0);assert.equal(h.el('#btnContinue').enabled,true);}ids.forEach((id,i)=>h.el('#'+id).value=values[i]);h.el('#inputGuestEmail').value='bad';await h.click();assert.equal(h.status(),'Please enter a valid email address.');assert.equal(h.calls.prepare,0);return {missingCombinations:7,malformedEmail:1,calls:h.calls};}
async function expiry(){const h=await harness();await h.click();h.s.clock.now+=3600000;await h.click();assert.match(h.status(),/unavailable or expired/);assert.equal(h.s.f.snapshot().GuestBookingAcceptances.length,0);assert.doesNotMatch(h.status(),/Booking confirmed|Booking number/);await h.click();assert.equal(h.calls.prepare,1);assert.equal(h.calls.confirm,1);return h.calls;}
async function afterAck(){let fail=true;const h=await harness({after:async kind=>{if(kind==='confirm'&&fail){fail=false;throw Error('response lost after actual acceptance');}}});await h.click();await h.click();assert.match(h.status(),/unknown/i);assert.equal(h.s.f.snapshot().GuestBookingAcceptances.length,1);await h.click();assert.match(h.status(),/still being saved/);assert.equal(h.s.f.snapshot().GuestBookingAcceptances.length,1);assert.equal(h.calls.prepare,1);return h.calls;}
const cases={CART01:cart,UNKNOWN01:unknown,PROMO01:promo,EDITS01:edits,REQUIRED01:required,EXPIRY01:expiry,ACK01:afterAck};const id=process.argv[2];assert.ok(cases[id]);const watchdog=setTimeout(()=>{console.error('page case watchdog');process.exit(2);},30000);cases[id]().then(result=>console.log(JSON.stringify({id,status:'PASS',result}))).catch(e=>{console.error(e.stack);process.exitCode=1;}).finally(()=>clearTimeout(watchdog));
