'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {setup,vector}=require('./business.cjs');
const root=path.resolve(__dirname,'../..'),copy=x=>JSON.parse(JSON.stringify(x));
function element(id){const handlers={};return {id,handlers,text:'',value:'',label:'Continue',link:'',target:'',hidden:false,collapsed:false,enabled:true,show(){this.hidden=false;},hide(){this.hidden=true;},expand(){this.collapsed=false;},collapse(){this.collapsed=true;},enable(){this.enabled=true;},disable(){this.enabled=false;},onClick(f){(handlers.click??=[]).push(f);},onInput(f){(handlers.input??=[]).push(f);},onChange(f){(handlers.change??=[]).push(f);},onBlur(f){(handlers.blur??=[]).push(f);},onKeyPress(f){(handlers.keypress??=[]).push(f);},onKeyDown(f){(handlers.keydown??=[]).push(f);},onItemReady(f){(handlers.item??=[]).push(f);},async fire(e='click',data={}){await Promise.all((handlers[e]||[]).map(f=>f(data)));}};}
async function harness(options={}){
 const s=setup(),api=s.load('guestBookingSummaryService.web'),calls={prepare:0,confirm:0,refresh:0,legacy:0,external:0},elements=new Map(),rows=[];
 const el=id=>{if(!elements.has(id))elements.set(id,element(id));return elements.get(id);};
 const $w=id=>el(id);let ready;$w.onReady=f=>ready=f;
 const rep=el('#summaryRoomsRepeater');Object.defineProperty(rep,'data',{get(){return this._data||[];},set(data){this._data=data;for(const item of data){const map=new Map(),itemEl=id=>{if(!map.has(id))map.set(id,element(id));return map.get(id);};rows.push({item,itemEl});for(const f of rep.handlers.item||[])f(itemEl,item);}}});
 const wire={};for(const [name,kind] of [['prepareGuestBookingSummary','prepare'],['confirmGuestBookingSummary','confirm'],['readGuestBookingSummaryStatus','refresh']])wire[name]=async x=>{calls[kind]++;if(options.before)await options.before(kind,x,s);const r=copy(await api[name](copy(x)));if(options.after)await options.after(kind,r,s);return r;};
 const controllerPath=fs.existsSync(path.join(root,'velo/public/bookConfirmSearch.js'))?'velo/public/bookConfirmSearch.js':'velo/page-book-confirm-search.js';
 const ctrl=vm.compileFunction(fs.readFileSync(path.join(root,controllerPath),'utf8').replace(/^import .*;$/gm,'').replace('export function ','function ')+'\nreturn {mountBookConfirmSearch};',Object.keys(wire))(...Object.values(wire));
 const forbidden=()=>{calls.external++;throw Error('external effect forbidden');};const legacy=()=>{calls.legacy++;throw Error('legacy booking forbidden');};
 const imports={'wix-location':{default:{query:{rc:vector.summaryRooms.map(r=>`${r.roomCode}:${r.qty}:${r.numGuests}:0`).join(','),ci:vector.purchase.checkIn,co:vector.purchase.checkOut,pkg:vector.purchase.packageId,quote:vector.purchase.pricingQuoteToken},to:forbidden}},'wix-data':{default:{query(name){assert.ok(['Rooms','PromoCodes','Packages'].includes(name),'frontend authority query forbidden '+name);return {hasSome(){return this;},eq(){return this;},limit(){return this;},async find(){return {items:[]};}};},update:forbidden}},'backend/settings':{getAllSettings:async()=>({})},'backend/rooms':{getRoomNames:async()=>({})},'backend/packages':{getPackagesByNights:async()=>[{_id:'package',baseRate:100,title:'Public connector fixture'}],getPackageBaseRate:async()=>100,getPackageAmenities:async()=>({}),getPackageDetailsByNights:async()=>({})},'backend/pricingQuotes':{readPricingQuote:async()=>JSON.parse(vector.quoteOriginalBytesUtf8)},'backend/availability':{createBooking:legacy,issueBookingInvoice:forbidden,validatePromoCode:async (...args)=>options.promo ? options.promo(...args) : ({valid:false,reason:'Promo code not found.'})},'public/tracking':{initTracking(){},setSuspendGoogleAds(){},getStoredClickIds:()=>({}),trackPurchase:forbidden,clearClickIds:forbidden},'backend/googleAdsConversions.web':{recordBookingConversion:forbidden},'backend/microsoftAdsConversions.web':{recordMicrosoftBookingConversion:forbidden},'public/bookConfirmSearch':ctrl};
 const source=fs.readFileSync(path.join(root,'velo/page-booking-summary.js'),'utf8');
 const transformed=source.replace(/^import\s+(.+?)\s+from\s+'([^']+)';\r?$/gm,(_,binding,spec)=>{assert.ok(imports[spec],'undeclared page import '+spec);return `const ${binding}=__import(${JSON.stringify(spec)})${binding.startsWith('{')?'':'.default'};`;});
 vm.compileFunction(transformed,['__import','$w','localStorage','console','setTimeout'],{filename:'ACTUAL-page-booking-summary.js'})(spec=>imports[spec],$w,{getItem:()=>null},{log(){},warn(){},error(){}},forbidden);
 el('#inputGuestName').value=vector.purchase.guestName;el('#inputGuestEmail').value=vector.purchase.guestEmail;el('#inputGuestPhone').value=vector.purchase.guestPhone;el('#inputDialingCode').value='1';
 ready();for(let i=0;i<100&&!el('#btnContinue').handlers.click?.length;i++)await new Promise(r=>setImmediate(r));assert.equal(el('#btnContinue').handlers.click?.length,1,'one actual Continue handler');
 return {s,calls,el,rows,source,click:()=>el('#btnContinue').fire(),status:()=>el('#bookingStatus').text};
}
async function main(){const h=await harness();assert.equal(h.el('#checkInDisplay').text,'1/1/2027');assert.equal(h.el('#checkOutDisplay').text,'1/5/2027');assert.equal(h.el('#summaryRoomsRepeater').data.length,2);
 const before=await h.s.load('search.web').searchAvailability(vector.purchase.checkIn,vector.purchase.checkOut);assert.equal(before.results.find(r=>r.roomCode==='adventure_suite').maxQty,3);
 await h.click();assert.equal(h.calls.legacy,0,'actual page must not invoke legacy createBooking');assert.equal(h.calls.prepare,1,'first page click prepares reviewed offer');assert.equal(h.calls.confirm,0);assert.equal(h.s.f.snapshot().GuestBookingAcceptances.length,0);assert.equal(h.el('#grandTotal').text,'$470.00');assert.match(h.el('#btnContinue').label,/Confirm/);
 const expected=copy(h.s.f.snapshot());h.el('#grandTotal').text='$0.01';
 await h.click();assert.equal(h.calls.confirm,1);assert.match(h.status(),/still being saved/);for(let i=0;i<64&&!/Booking confirmed/.test(h.status());i++){assert.doesNotMatch(h.status(),/Booking number/);await h.click();}assert.match(h.status(),/Booking confirmed/);assert.equal(h.s.f.snapshot().Bookings.length,2);assert.equal(h.s.f.snapshot().GuestBookingCompletions.length,1);assert.equal(h.calls.external,0);assert.doesNotMatch(h.status(),/emailed|home|redirect/i);
 const db=h.s.f.snapshot(),receipt=db.GuestBookingCompletions[0];
 const projection=JSON.parse(receipt.projectionCanonical);assert.equal(projection.summary.acceptedCalculation.totals.grandTotalCents,47000);assert.equal(h.el('#grandTotal').text,'$470.00');
 const after=await h.s.load('search.web').searchAvailability(vector.purchase.checkIn,vector.purchase.checkOut);assert.equal(after.ok,true);assert.equal(after.results.length,0);
 const rules=h.s.load('roomAssignmentRules');assert.equal(rules.ownerUnitForOccupiedUnits([3,4]),5);assert.deepEqual(rules.chooseAutomaticUnits('adventure_suite',1,[3,4]),[]);assert.deepEqual(rules.chooseAutomaticUnits('adventure_suite',3,[]),[3,4,5]);
 const inventory=await h.s.load('roomInventory').loadInventorySnapshot(vector.purchase.checkIn,vector.purchase.checkOut);for(const night of Object.keys(inventory.occupiedUnitsByNight)){assert.deepEqual(inventory.occupiedUnitsByNight[night],[3,4]);assert.equal(inventory.occupiedCapacityByNight[night],2);}
 const calls=copy(h.calls);await h.click();assert.deepEqual(h.calls,calls);
 fs.writeFileSync(path.join(__dirname,'evidence/page-actual-history.json'),JSON.stringify({db,trace:h.s.f.trace,before,after,inventory,ownerBlockedUnit:5,calls:h.calls},null,2));
 console.log(JSON.stringify({id:'PAGE01',status:'PASS',calls:h.calls,statusText:h.status(),total:h.el('#grandTotal').text}));}
if(require.main===module)main().catch(e=>{console.error(e.stack);process.exitCode=1;});module.exports={harness,copy,root};
