'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {setup,vector}=require('./business.cjs'),{createLoader}=require('./loader.cjs');
const admission=JSON.parse(fs.readFileSync(path.join(__dirname,'business-admission.json')));
const ci=vector.purchase.checkIn,co=vector.purchase.checkOut;
function save(id,s,extra={}){fs.writeFileSync(path.join(__dirname,'evidence',id+'-history.json'),JSON.stringify({db:s.f.snapshot(),trace:s.f.trace,...extra},null,2));}
async function accept(s){const connector=s.load('guestBookingSummaryStatusConnector').createGuestBookingSummaryStatusConnector();const {priceGroups,...input}=vector.purchase;const offer=await connector.prepare({...input,summaryRooms:vector.summaryRooms});assert.equal(offer.status,'OFFER');const result=await connector.confirm(offer);assert.ok(['ACCEPTED_PENDING','UNKNOWN'].includes(result.status));assert.equal(s.f.snapshot().GuestBookingAcceptances.length,1);return {connector,offer};}
async function recover(s){for(let i=0;i<64&&!s.f.snapshot().GuestBookingCompletions.length;i++)await s.load('guestBookingCompletionRecovery').recoverGuestBookingCompletions();assert.equal(s.f.snapshot().GuestBookingCompletions.length,1);}
async function inventory(){const s=setup();await accept(s);const observations=[];try{for(let i=0;i<64;i++){
 const e=await s.load('guestBookingAllocationEvidence').readGuestBookingAllocationEvidence(ci,co);assert.equal(e.status,'READY');
 let max=0;for(let quantity=1;quantity<=3;quantity++){try{s.load('roomBookingCommitRules').buildPhysicalCommitPlanFromSources(e.planningEvidence,{checkIn:ci,checkOut:co,roomCode:'adventure_suite',quantity,bookingNumber:'PLANNING-ONLY',operationId:'planning_only_no_writes',payloadDigest:'a'.repeat(64)});max=quantity;}catch{}}
 const result=await s.load('search.web').searchAvailability(ci,co);assert.equal(result.ok,true);const searchMax=result.results.find(x=>x.roomCode==='adventure_suite')?.maxQty??0;
 observations.push({quantum:i,max,searchMax,claims:s.f.snapshot().RoomBookingClaimEvents.length,bookings:s.f.snapshot().Bookings.length,receipts:s.f.snapshot().GuestBookingCompletions.length});assert.equal(searchMax,max,'actual allocator/Search prefix parity');
 if(s.f.snapshot().GuestBookingCompletions.length)break;await s.load('guestBookingCompletionRecovery').recoverGuestBookingCompletions();
 }assert.equal(s.f.snapshot().GuestBookingCompletions.length,1);
 s.f.armFault('read','HotelClosures');assert.equal((await s.load('search.web').searchAvailability(ci,co)).ok,false,'closure uncertainty must fail closed');
 return {id:'INVENTORY01',status:'PASS',observations};}finally{save('INVENTORY01',s,{observations});}}
async function retry(){const s=setup();s.f.armFault('after-apply','GuestBookingAcceptances');const {connector,offer}=await accept(s);await connector.confirm(offer);assert.equal(s.f.snapshot().GuestBookingAcceptances.length,1);s.f.armFault('after-apply','Bookings');s.f.armFault('after-apply','GuestBookingCompletions');
 for(let i=0;i<10;i++)await s.load('guestBookingCompletionRecovery').recoverGuestBookingCompletions();const old=s.load('guestBookingCompletionRecovery'),loader=createLoader(s.f,s.clock,admission);s.load=n=>loader.load('velo/backend/'+n+'.js');assert.notEqual(old,s.load('guestBookingCompletionRecovery'));await recover(s);const before=JSON.stringify(s.f.snapshot().Bookings);for(let i=0;i<3;i++)await s.load('guestBookingCompletionRecovery').recoverGuestBookingCompletions();assert.equal(JSON.stringify(s.f.snapshot().Bookings),before);assert.equal(s.f.snapshot().Bookings.length,2);assert.equal(s.f.snapshot().BookingSummary.length,1);assert.equal((await connector.readStatus(offer)).status,'CONFIRMED');save('RETRY01',s);return {id:'RETRY01',status:'PASS'};}
async function legacy(){const row={_id:'synthetic-legacy-qty2',bookingNumber:'SYNTHETIC-NOT-WC-1028',roomCode:'adventure_suite',quantity:2,assignedRoom:3,status:'confirmed',checkIn:ci,checkOut:co,guests:4,roomFee:123.45};const s=setup({Bookings:[row]});const before=JSON.stringify(s.f.snapshot().Bookings);try{const result=await s.load('search.web').searchAvailability(ci,co);assert.equal(result.ok,true,'synthetic quantity2 must remain searchable');assert.equal(result.results.find(x=>x.roomCode==='adventure_suite')?.maxQty??0,0);const e=await s.load('guestBookingAllocationEvidence').readGuestBookingAllocationEvidence(ci,co);assert.equal(e.status,'READY');const constraints=s.load('guestBookingAllocationSourceRules').allocationConstraintsFromSources(e.planningEvidence,ci,co);assert.deepEqual(constraints.effectiveSnapshot.occupiedUnits,[3,4]);assert.equal(JSON.stringify(s.f.snapshot().Bookings),before);return {id:'LEGACY01',status:'PASS',qualification:'SYNTHETIC_MULTIQUANTITY_NOT_WC1028'};}finally{save('LEGACY01',s);}}
async function auth(){const s=setup(),{connector,offer}=await accept(s);const count=s.f.trace.length;assert.equal((await connector.confirm(JSON.parse(JSON.stringify(offer)))).status,'DENIED');assert.equal(s.f.trace.length,count);connector.invalidate();assert.equal((await connector.readStatus(offer)).status,'DENIED');await recover(s);s.clock.now=offer.offerExpiresAtMs;assert.equal((await connector.confirm(offer)).status,'DENIED');assert.equal(s.f.snapshot().GuestBookingCompletions.length,1);save('AUTH01',s);return {id:'AUTH01',status:'PASS',qualification:'private handle controls; serialized boundary still missing'};}
const selectors={INVENTORY01:inventory,RETRY01:retry,LEGACY01:legacy,AUTH01:auth};
if(require.main===module){const fn=selectors[process.argv[2]];if(!fn)throw Error('exact scenario selector required');fn().then(x=>{fs.writeFileSync(path.join(__dirname,'evidence',x.id+'-result.json'),JSON.stringify(x,null,2));console.log(JSON.stringify(x));}).catch(e=>{console.error(e.stack);process.exitCode=1;});}
module.exports={...selectors,accept,recover,save};
