'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {setup,vector}=require('./business.cjs');
const copy=x=>JSON.parse(JSON.stringify(x));
async function run(){const s=setup(),api=s.load('guestBookingSummaryService.web');assert.equal(typeof api.prepareGuestBookingSummary,'function','serialized Summary service required');
 const source=fs.readFileSync(path.join(__dirname,'../../velo/page-book-confirm-search.js'),'utf8');const exported=vm.compileFunction(source.replace(/^import .*;$/gm,'').replace(/export function /g,'function ')+'\nreturn {mountBookConfirmSearch};',['prepareGuestBookingSummary','confirmGuestBookingSummary','readGuestBookingSummaryStatus','Date'])(async x=>copy(await api.prepareGuestBookingSummary(copy(x))),async x=>copy(await api.confirmGuestBookingSummary(copy(x))),async x=>copy(await api.readGuestBookingSummaryStatus(copy(x))),Date);
 const events=[],callbacks={},ui={onConfirm:fn=>callbacks.confirm=fn,onRefresh:fn=>callbacks.refresh=fn,render:state=>events.push(copy(state))};const page=exported.mountBookConfirmSearch(ui);const {priceGroups,...input}=vector.purchase;await page.prepare({...input,summaryRooms:vector.summaryRooms});assert.equal(events.at(-1).status,'OFFER');assert.equal(s.f.snapshot().GuestBookingAcceptances.length,0);
 await callbacks.confirm();for(let i=0;i<64&&events.at(-1).status!=='CONFIRMED';i++)await callbacks.refresh();assert.equal(events.at(-1).status,'CONFIRMED');assert.equal(s.f.snapshot().GuestBookingCompletions.length,1);assert.equal(s.f.snapshot().Bookings.length,2);const search=await s.load('search.web').searchAvailability(vector.purchase.checkIn,vector.purchase.checkOut);assert.equal(search.ok,true);assert.equal(search.results.length,0);assert.ok(events.filter(x=>x.status!=='CONFIRMED').every(x=>!x.bookingNumber));
 fs.writeFileSync(path.join(__dirname,'evidence/serialized-e2e-history.json'),JSON.stringify({events,db:s.f.snapshot(),trace:s.f.trace},null,2));return {id:'E2E01',status:'PASS',boundary:'actual candidate serialized service and mounted page callbacks'};}
if(require.main===module)run().then(x=>console.log(JSON.stringify(x))).catch(e=>{console.error(e.stack);process.exitCode=1;});module.exports={run};
