'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {setup,vector}=require('./business.cjs'),{createLoader}=require('./loader.cjs'),{recover,save}=require('./scenarios.cjs');
const copy=x=>JSON.parse(JSON.stringify(x)),admission=JSON.parse(fs.readFileSync(path.join(__dirname,'business-admission.json')));
const input=()=>{const {priceGroups,...rest}=vector.purchase;return {...rest,summaryRooms:vector.summaryRooms};};
function mount(api,tap=async x=>x){const source=fs.readFileSync(path.join(__dirname,'../../velo/page-book-confirm-search.js'),'utf8');const fn=vm.compileFunction(source.replace(/^import .*;$/gm,'').replace(/export function /g,'function ')+'\nreturn mountBookConfirmSearch;',['prepareGuestBookingSummary','confirmGuestBookingSummary','readGuestBookingSummaryStatus'])(async x=>tap(copy(await api.prepareGuestBookingSummary(copy(x)))),async x=>copy(await api.confirmGuestBookingSummary(copy(x))),async x=>copy(await api.readGuestBookingSummaryStatus(copy(x))));const events=[],callbacks={};const page=fn({onConfirm:fn=>callbacks.confirm=fn,onRefresh:fn=>callbacks.refresh=fn,render:x=>events.push(copy(x))});return {page,events,callbacks};}
async function run(){const cases=[],s=setup();let api=s.load('guestBookingSummaryService.web');const offer=await api.prepareGuestBookingSummary(input());assert.equal(offer.status,'OFFER');const before=JSON.stringify(s.f.snapshot());
for(const bad of [{bookingNumber:'anything'},{...offer.credential,token:offer.credential.token+'x'},{...offer.credential,capsule:offer.credential.capsule+' '},{...offer.credential,extra:1}]){assert.equal((await api.confirmGuestBookingSummary(copy(bad))).status,'DENIED');assert.equal((await api.readGuestBookingSummaryStatus(copy(bad))).status,'DENIED');assert.equal(JSON.stringify(s.f.snapshot()),before);}cases.push('wire-tamper-no-authority-writes');
s.f.armFault('after-apply','GuestBookingAcceptances');let accepted=await api.confirmGuestBookingSummary(copy(offer.credential));assert.ok(['UNKNOWN','ACCEPTED_PENDING'].includes(accepted.status));assert.ok(!accepted.bookingNumber);assert.equal(s.f.snapshot().GuestBookingAcceptances.length,1);
const loader=createLoader(s.f,s.clock,admission),old=api;api=loader.load('velo/backend/guestBookingSummaryService.web.js');assert.notEqual(api,old);accepted=await api.confirmGuestBookingSummary(copy(offer.credential));assert.equal(accepted.status,'ACCEPTED_PENDING');assert.equal(s.f.snapshot().GuestBookingAcceptances.length,1);cases.push('wire-lost-ack-new-module-same-credential');
s.clock.now=offer.offerExpiresAtMs;const expiredBefore=JSON.stringify(s.f.snapshot());assert.equal((await api.confirmGuestBookingSummary(copy(offer.credential))).status,'DENIED');assert.equal((await api.readGuestBookingSummaryStatus(copy(offer.credential))).status,'DENIED');assert.equal(JSON.stringify(s.f.snapshot()),expiredBefore);await recover(s);assert.equal(s.f.snapshot().GuestBookingCompletions.length,1);assert.equal((await api.readGuestBookingSummaryStatus(copy(offer.credential))).status,'DENIED');cases.push('wire-exact-expiry-durable-recovery-no-disclosure');save('AUTH01-wire',s,{cases});
const t=setup(),service=t.load('guestBookingSummaryService.web');let release,arrive;const arrived=new Promise(r=>arrive=r),gate=new Promise(r=>release=r);const ui=mount(service,async x=>{arrive();await gate;return x;});const watchdog=setTimeout(()=>{release();},10000);
try{const pending=ui.page.prepare(input());await arrived;ui.page.invalidate();release();await pending;assert.equal(ui.events.at(-1).status,'STALE');await ui.callbacks.confirm();assert.equal(t.f.snapshot().GuestBookingAcceptances.length,0);cases.push('page-delayed-offer-invalidated-zero-acceptance');}finally{clearTimeout(watchdog);release();}
const u=mount(service);await u.page.prepare(input());const p1=u.callbacks.confirm(),p2=u.callbacks.confirm();await Promise.all([p1,p2]);assert.equal(t.f.snapshot().GuestBookingAcceptances.length,1);assert.ok(u.events.every(x=>!x.bookingNumber));u.page.invalidate();await u.callbacks.refresh();assert.equal(u.events.at(-1).status,'STALE');cases.push('page-double-click-single-root-and-stale-refresh');assert.equal(cases.length,5);save('AUTH01-page',t,{cases});return {id:'AUTH01',status:'PASS',cases};}
if(require.main===module)run().then(x=>{fs.writeFileSync(path.join(__dirname,'evidence/AUTH01-wire-result.json'),JSON.stringify(x,null,2));console.log(JSON.stringify(x));}).catch(e=>{console.error(e.stack);process.exitCode=1;});module.exports={run};
